### PR TITLE
feat: add rust-cargo-integration template

### PR DESCRIPTION
**Pull request by 90-008**
This adds a Rust template that uses https://github.com/yusdacra/nix-cargo-integration. The template is adapted from https://github.com/yusdacra/rust-nix-templater 's template files.

### CODE REVIEW

**Comment by i077** [comment]
Thank you for submitting a template! Could you also add `flake-compat` to your list of flake inputs and import it from there in `shell.nix`, just so it's consistent with the other templates?

I also see our CI runner is being rate-limited by GitHub, so I'll have to give Nix a token.

**Comment by i077** [comment]
Can you also rebase your branch? I just merged #11.

**Comment by 90-008** [comment]
Alright, that should be done now.

**Comment by i077** [comment]
You don't seem to have a shell output for macOS users, which is something we want to have for all templates. Are you able to add that in yours?

**Comment by 90-008** [comment]
> You don't seem to have a shell output for macOS users, which is something we want to have for all templates. Are you able to add that in yours?

Oops sorry, it seems I forgot to add `x86_64-darwin` to systems. It is done now.

**Review by i077 — APPROVED** [review]
LGTM

**Pull request merged**
